on:
  push:
    branches:
      - master

name: 🚀 Deploy React app on push

jobs:
  deploy:
    name: 🎉 Deploy React app
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v2

      - name: 🛠 Build React app
        env:
          CI: false
        run: |
          cd x-ads-partisia
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: premium190.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./x-ads-partisia/build/
